[package]
name = "dpbst-cli"
description = "Command line front end for the dpbst SAT solver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "dpbst"
path = "src/main.rs"

[dependencies]
dpbst-core.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
